<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;
use AppBundle\Entity\Category;

/**
 * FortuneCookieRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FortuneCookieRepository extends EntityRepository
{
  public function countNumberForCategory(Category $category){
    return $this->createQueryBuilder('fc')
      ->andWhere('fc.category = :category')
      ->setParameter('category', $category);
  }
}
